// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfvjdtzkznjjjjxctyoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmdmpkdHprem5qampqeGN0eW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTc5NzgsImV4cCI6MjA2OTM3Mzk3OH0.KTQOb7mHYL-rye6IVRU_Htydpmgw_2QOVP0EwOprtw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});